server:
  port: 8789

spring:
  application:
    name: treasure-box
  datasource:
    url: jdbc:mysql://localhost:3306/treasure_box?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      database: 0
      timeout: 6000
      cluster:
        nodes: 192.168.2.76:7001,192.168.2.76:7002,192.168.2.76:7003,192.168.2.76:7004,192.168.2.76:7005,192.168.2.76:7006
      lettuce:
        pool:
          max-active: 1000
          max-wait: -1
          max-idle: 10
          min-idle: 5

# MyBatis 配置
mybatis:
  # 指定Mapper XML文件的位置
  mapper-locations: classpath:mapper/*.xml
  # 指定实体类的包路径，可省略全限定类名
#  type-aliases-package: com.douniu.box.mapper.entity
  configuration:
    # 开启驼峰命名转换（如数据库字段user_name转成实体类属性userName）
    map-underscore-to-camel-case: true
    # 打印SQL语句（开发环境建议开启，生产环境关闭）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl